CREATE DATABASE <POSTGRESQL-DB-NAME>;
CREATE USER <POSTGRESQL-USER> WITH PASSWORD '<POSTGRESQL-PWD>';
ALTER ROLE <POSTGRESQL-USER> SET client_encoding TO 'utf8';
ALTER ROLE <POSTGRESQL-USER> SET default_transaction_isolation TO 'read committed';
ALTER ROLE <POSTGRESQL-USER> SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE <POSTGRESQL-DB-NAME> TO <POSTGRESQL-USER>;